yajra/laravel-datatables

src/yajra/Datatables/Datatables.php

Hi Arjay, 
I have discovered an issue when creating a new Request instance by passing in the GET and POST superglobals, the Request method will default to GET and somehow this resulted with `$request->input()` returning an empty array in case of POST requests. This was because the server superglobal was not passed in the Request constructor. Please see [this link](https://github.com/symfony/HttpFoundation/blob/master/Request.php#L1339) related to Request method defaulting to GET if the server array is empty.
This issue lead to the initial datatable being populated with data but pagination or limiting would not work as the the server would always return the same results due to input being empty.
This change will use the Request's built in `capture()` method which will return a fully set up …

FIX: request input to call built in capture() to retrieve new instance

---

src/yajra/Datatables/Engine/BaseEngine.php

Multiple backtick symbol is generated when doing filtering by column. 
An example of generated query before fix:
SQLSTATE[42S22]: Column not found: 1054 Unknown column '`email`' in 'where clause' (SQL: select count(*) as aggregate from (select '1' as row_count from `subscriptions` where `user_id` = 1 and ```email``` LIKE %test%) count_row_table)

Fix for multiple backtick (`) on column filtering

---

src/yajra/Datatables/Engines/BaseEngine.php
src/yajra/Datatables/Engines/QueryBuilderEngine.php

Added orderColumn feature allowing users to override the default ordering of a column. Laravel's orderByRaw is used by default. An internal parameter '$1' is available which returns the requested order of the column.
```php
//**
* Override default column ordering.
*
* @param string $column
* @param string $sql
* @param array $bindings
* @return $this
* @internal string $1 Special variable that returns the requested order direction of the column.
*/
public function orderColumn($column, $sql, $bindings = [])
```
Example code will hijack remember_token ordering and use order by name instead.
```php
return Datatables::of(User::select('*'))
->orderColumn('remember_token', 'name $1')
->make(true);
```

[Feature] orderColumn

---

readme.md

Add provider to vendor publish command.
Only publish the package configuration for this package. With the other command, we are publishing all the config files

Only publish package configuration

---

src/yajra/Datatables/Engines/QueryBuilderEngine.php

If we perform a select("*"), the ORDER BY clause will look like this: `ORDER BY * ASC` which causes a query exception.
The temporary fix is modifying `*` column to `id` column.

QueryBuilder: ORDER BY *

---

src/yajra/Datatables/Engines/CollectionEngine.php

serialize seems to work (already does in filtering) for relation columns (flattening the relation to array and accessing the column with dot notation)

collectionengine: fix sorting of relation columns by using seralize

---

src/yajra/Datatables/Datatables.php

'column as name' was showing up in $this->columns[$order_col] and it could not sort by that string.

added a getColumnName

---

src/yajra/Datatables/Datatables.php

Allow it to grab the last 'as' in a multi-line select query (within a select query). Also does one line.
Would solve something complicated like this:
```php
->select('table.begin_at', DB::raw('(SELECT table2.id FROM table as t ...) as file_id'))
```
We'll be on L4 for a while due to a large project, hope you don't mind the requests.

sort by a multi-line 'select as' query

---

src/yajra/Datatables/Engines/QueryBuilderEngine.php

so we can take the field in the database in any order, because in this way the name of the field does not depend on the order of the query sql but the parameter's request "column"

get order column name from the request

---

src/Helper.php
tests/HelperTest.php

Fix for Issue: yajra/laravel-datatables#385

Fix addColumn fails when order falls at end of array

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php
src/config/config.php

Before this change, regex statements were generated with the MySQL operator 'REGEXP', which were leading to a Oracle error.
Now it uses the Oracle Database SQL function 'REGEXP_LIKE', as written in the Oracle Database Online Documentation, 10g Release 2 (10.2) .

Change how regex code is generated after a column search.

---

src/Engines/CollectionEngine.php

With this small change filtering is working even with nested columns, using dot notation.

Fix filtering in nested columns of Collections

---

src/Processors/DataProcessor.php

For example you have `User` and `Phone` models. `User` has one `Phone`.  `Phone` has `name` field
And you want to edit phone.name field. My pull request allow to do it:
```
$users = User::with('phone');
\Datatables::of($users)
->editColumn('phone.name', function($user) {
return 'Name of phone is: ' . $user->phone->name;
})
->make(true);
```

Allow edit columns for nested arrays

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php

Hello,
with the following PR I have added a closure support for filterColumn method as a more advanced and flexible way of customising things.
Instead of writing like this:
```php
->filterColumn('id', 'whereRaw', 'interface_strings.interface_string_id = ?', [$request->get('columns')[0]['search']['value']])
```
we can now use like this ($keyword supplied to a closure is without wildcards - especially handy when we want to do an exact match):
```php
->filterColumn('id', function($query, $keyword) {
$query->where('interface_strings.interface_string_id', $keyword);
})
```
Exact match issues specified in #217, #191 should be covered by this PR.
Looking forward!

Added Closure support for filterColumn method

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php

This PR will add `blacklist` and `whitelist` feature that addresses concerns where user can search en sort on fields that are not specified in the query like issue #260.
```php
$users = User::query();
return Datatables::of($users)
->whitelist('*')
->blacklist(['password', 'email'])
->make(true);
```
In case both functions are used at the same time, blacklist will be prioritized.

Add blacklist and whitelist feature.

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php
src/config/config.php

This PR will add DataTables option to disable smart search via config or during runtime. Addresses issue #423.
```php
$users = User::select(['id', 'name', 'email', 'created_at', 'updated_at']);
return Datatables::of($users)->smart(false)->make(true);
```
```php
'search' => [
'smart'            => true,
'case_insensitive' => true,
'use_wildcards'    => false,
],
```

[Proposal] Add smart search config option. Fix #423

---

src/Html/Builder.php
src/Html/Column.php
tests/HtmlBuilderTest.php

This PR will add an option to add a table footer via Builder. Footer contents will be defined via column definition.
```php
$builder->columns([
'id' => ['footer' => 'footer content']
]);
$dataTable->table([], true); // passing true as second parameter will draw the footer.
```

Add option to create a table footer from builder defined via column def

---

src/Engines/QueryBuilderEngine.php

This should fix any issues one might have when using a HasOne relation.
The API to get a foreign and other key are different then other relation types.
I believe it should also fix issue #567

HasOne relation uses different methods to get foreign and other key

---

src/Generators/DataTablesMakeCommand.php
src/Generators/stubs/datatables.stub
src/config/config.php

This PR will:
- Add model option to dataTable command.
- Make generator namespace configurable.
- Add filename in generator with timestamps.
Usage:
`php artisan datatables:make Post --model`
Output:
```php
<?php
namespace App\DataTables;
use App\Post;
use Yajra\Datatables\Services\DataTable;
class PostDataTable extends DataTable
{
/**
* Display ajax response.
*
* @return \Illuminate\Http\JsonResponse
*/
public function ajax()
{
return $this->datatables
->eloquent($this->query())
->addColumn('action', 'path.to.action.view')
->make(true);
}
/**
* Get the query object to be processed by dataTables.
*
* @return \Illuminate\Database\Eloquent\Builder|\Illuminate\Database\Query\Builder|\Illuminate\Support\Collection
*/
public function query()
{
$query = Post::query();
return …
```

Add model option to dataTable command.

---

composer.json
src/Services/DataTable.php
src/Transformers/DataTransformer.php
src/config/config.php
src/resources/views/print.blade.php

This PR will enhance the process of exporting dataTable to PDF with some minor bug fixes.
- Add support for snappy pdf via config.
- Add laravel-snappy on suggested packages.
- Add table stripes style.
- Fix printing template when value is an array.
- Fix issue when exporting pdf and data can't be decoded.
- ErrorException in DataTransformer.php line 67:
strip_tags() expects parameter 1 to be string, array given
Usage:
- Install [laravel-snappy](https://github.com/barryvdh/laravel-snappy).
- Update `datatables.php` config and use `snappy` as the pdf generator:
```php
'pdf_generator' => 'snappy'
```

Export PDF enhancements

---

src/yajra/Datatables/Datatables.php
tests/DatatablesBuilder.php

The method `$myQuery->getBindings()` ([src/yajra/Datatables/Datatables.php#L337](https://github.com/yajra/laravel-datatables/blob/599aab0541ff0cb64f44db3618978d2685a03afc/src/yajra/Datatables/Datatables.php#L337)) returns _all_ bindings, including any bindings to the select statement. But since the select statement is overwritten these bindings can be incorrect.
```php
public function getTableData()
{
$query = \DB::table(\DB::raw('`calls` `call`'))
->selectRaw('
`call`.`id`,
`call`.`created_at`,
`company`.`name` AS `company_name`,
`company`.`id` AS `company_id`,
`call`.`short_description`,
`call`.`estimated_hours`,
`call`.`type`,
`call`.`status`,
`call`.`due_at`,
`call`.`closed_at`,
`assignee`.`id` AS `assignee_id`,
CASE
WHEN SUM(`time`.`hours`) IS NULL THEN 0
ELSE SUM(`time`.`hours`)
END …
```

Unset any bindings to select statement

---

.travis.yml
src/Helper.php

This PR will:
- Fix the issue where a record is being deleted by LDT when column name used is `delete`.
- Fix helper doc blocks.
- Fix #565 and #640.
- Allow travis-ci failure on HHVM. Mostly due to execution timestamp.

Fix issue where a record is being deleted.

---

src/Contracts/DataTableEngineContract.php
src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php
src/Engines/QueryBuilderEngine.php

This PR will allow global search to work along with filter callback.
Addresses issues like: https://github.com/yajra/laravel-datatables/issues/94
Just add `true` as the second parameter of `filter()` method:
```php
public function filter(\Closure $callback, $globalSearch = false);
```
```php
public function ajax()
{
return $this->datatables
->queryBuilder($this->query())
->filter(function (Builder $query) {
if ($type = $this->request()->get('name')) {
$query->where('name', $type);
}
}, true)
->make(true);
}
```

Allow global search to work with custom filter callback.

---

src/Engines/BaseEngine.php

In my use case, the transformer constructor that I provide has arguments which are lost because of re-instancing the transformer.
This patch allows for creating a transformer instance if the class name is provided, otherwise, if an instance is provided, it keeps it.

Transformer instance is kept, otherwise new instance is created.

---

src/Engines/BaseEngine.php

This PR will add `orderColumns` api helper that can help us in cases where we want to apply a custom order sql for each columns.
In some cases, we may want to sort our columns where null values will be last on display. To achieve this in dataTables we can use `orderColumn` for each column. Or we can use `orderColumns` and pass all the columns array to avoid duplication of codes.
For Oracle:
```php
$users = User::query();
return Datatables::of($users)
->orderColumns(['name', 'email'], ':column $1 nulls last')
->make(true);
```
For MySQL:
```php
->orderColumns(['name', 'email'], '-:column $1')
```
When using the service approach:
```php
->orderColumns(Arr::pluck($this->getColumns(), 'name'), ':column $1 nulls last')
```

Add orderColumns api helper.

---

src/Html/Builder.php
tests/HtmlBuilderTest.php

Useful for settings attributes.
Maybe in the future, using `__set` and `__get`?

Add setter and getter for table attributes.

---

src/Engines/CollectionEngine.php

This PR fixes scenario that may occur when you manually set the total records and the paging will exceed the expected total.

If filtered total > total records, use total records.

---

src/Engines/QueryBuilderEngine.php

Hi
I was having issues implementing column search for a column showing data from a eager loaded HasMany-relationship. Treating HasMany in the same way as HasOne fixed it for me as HasMany has the getForeignKey()-method as well.
See the issue i created: #732

Fix to allow join of eager loaded column based on a HasMany-relationship

---

src/Engines/CollectionEngine.php

The QueryBuilderEngine has support for using Oracle queries to search for regular expressions when a columns 'regex' flag is enabled. This update adds similar functionality to the CollectionEngine using PHP's built-in preg functions.

Support regex column searches when using CollectionEngine

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php

This is required when a user uses a model with soft deletes trait (use Illuminate\Database\Eloquent\SoftDeletes), but does not include to select trashed items (withTrashed()), then the number of selected elements and elements in the pagination begins to differ.
Commit adds the ability to manage it and select or not deleted records in count function

Support of using soft deletes trait in models.

---

src/Engines/QueryBuilderEngine.php

This PR will:
* Do not convert column to raw statement.
* Force user to use Laravel's Expression or DB::raw, for raw statements.
* Fix a possible SQL Injection attack.

Do not convert column to raw statement.

---

src/Engines/BaseEngine.php

This will allow the package to return the original serializer instance if new instance was passed.
```php
Datatables::of($query)->setSerializer(new ArraySerializer)->make(true);
```

[6.0] Add method to get or create a transformer serializer.

---

src/Engines/BaseEngine.php

Replaces `\Closure` with `callable`.

[6.0] Use callable type hint.

---

src/config/config.php
src/yajra/Datatables/Datatables.php

Accept auto filter when we call filter function. Added to avoid the probleme of rapid search inbox with the personnel filter.
```
return Datatables::of($activities)->filter(function ($query) {
$input = Input::all();
if(Input::has('rfs'))
$query->where('refstan', 'ilike', '%'.Input::get('rfs').'%');
}, true)->make(true);
```
Order by nulls last function.
```
return Datatables::of($activities)->orderByNullsLast()->make(true);
```

add override auto filter and add ordering by nulls last

---

src/Engines/QueryBuilderEngine.php

Ambiguous field error will appear when search and join relations together.
This patch will only get table from builder class and push it before column name.
_This patch need for next pull request that I about sort in nested relations._

Patch for fix ambiguous field error for relations.

---

src/resources/views/print.blade.php

getting issue when data like below 
Array
(
[0] => Array
(
[Object] => Buyer
[Sub Type] => Plot
)
[1] => Array
(
[Object] => Buyer
[Sub Type] => Office Shop
)
[2] => Array
(
[Object] => Buyer
[Sub Type] => Bunglow
)
[3] => Array
(
[Object] => Buyer
[Sub Type] => Plot
)
[4] => Array
(
[Object] => Buyer
[Sub Type] => Plot
)
[5] => Array
(
[Object] => Seller
[Sub Type] => Plot
)
[6] => Array
(
[Object] => Seller
[Sub Type] => Plot
)
[7] => Array
(
[Object] => Seller
[Sub Type] => Plot
)
[8] => Array
(
[Object] => To Let
[Sub Type] => Plot
)
[9] => Array
(
[Object] => Rent
[Sub Type] => Flat
)
)
first row repeated more time
if data like above then header repeated so i add flag for first row

Fix print header issue when two row are same value

---

src/DatatablesServiceProvider.php

Adding alias for `Datatables` class, then `app('datatables')`, `app(Datatables::class)`, and method dependency of `Datatables` will be the same singleton instance.

Fix singleton

---

src/Engines/BaseEngine.php
src/Engines/EloquentEngine.php
src/Engines/QueryBuilderEngine.php

- Add support for onlyTrashed model scope. Fix #928
- Move withTrashed method to Eloquent engine.
```php
$shops = Shop::select('shops.*')->onlyTrashed();        
return Datatables::of($shops)->onlyTrashed()->make(true);
```

[6.0] Add support for onlyTrashed model scope. Fix #928

---

src/Engines/QueryBuilderEngine.php

Getting error when using pgsql database and activate the regex filtering.
```
SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "REGEXP"
LINE 1: ...s "row_count" from "categories" where LOWER(name) REGEXP $1)...
```
on postgreSQL there is no REGEXP command. We can use [POSIX regular expression](https://www.postgresql.org/docs/9.3/static/functions-matching.html#FUNCTIONS-POSIX-TABLE)

Fix regex query for pgsql.

---

src/Engines/QueryBuilderEngine.php

Pull the existing bindings from the builder and prepare the first element based on our configuration. Doing so we also pull any extra bindings that the builder has.
Dow now this was tested ONLY with relationships similar to:
```php
return $this->hasOne('App\FieldOption', 'sort_order', 'service')
->where('group_id', '=', '1');
```

[7.0] Add support for 'where' in the relationship

---

src/Datatables.php
tests/Integration/CollectionEngineTest.php

Idea came from this [Laracast Forum](https://laracasts.com/discuss/channels/general-discussion/datatables-from-a-raw-query) question.
Examples:
```php
$source = [
[1, 2, 3],
[4, 5, 6],
];
return Datatables::of($source)->make();
```
```php
$source = DB::select('select * from users');
return Datatables::of($source)->make(true);
```

[7.0] Add support for array data source.

---

src/Engines/QueryBuilderEngine.php

Same commit as #850, updated for v7
I don't know if this is related, but I had to change
$columns = $this->request->columns();
back to
$columns = (array) $this->request->input('columns');
for some datatables (method not supported)

[7.0] Add support ordering when search in nested relations

---

src/DatatablesServiceProvider.php

Correct me if I'm missing something but this is not needed and used here as you already moved the HTML builder as an another plugin where you also register it [there](https://github.com/yajra/laravel-datatables-html/blob/master/src/HtmlServiceProvider.php#L52).

[7.0] Remove HtmlServiceProvider which is not being used.

---

composer.json

Bumped dompdf version to 0.8 for compatability with barryvdh/laravel-dompdf

bump to 0.8 dompdf for compatability with barryvdh/dompdf

---

src/Html/Builder.php

The Editor buttons used for Datatables Editor when added to attribute list generates Javascript JSON code that has editor variable wrapped around with double quotes. which is treated as string in javascript instead of variable. This code change removes additionally added double quotes.
For more detailed information you can look at issue "Adding Editor buttons" #1095

[6.0] Formatting the attributes for Editor buttons.

---

src/config/datatables.php

Do not use ::class to avoid IDE error when fractal is not installed.

[7.0] Do not use ::class to avoid IDE error when fractal is not installed.

---

src/Engines/BaseEngine.php
src/Exception.php
src/config/datatables.php

* When app is in production, it is better to display a custom error message to the user.
* Implements server-side error handling as defined on https://datatables.net/manual/server-side.
> Optional: If an error occurs during the running of the server-side processing script, you can inform the user of this error by passing back the error message to be displayed using this parameter. Do not include if there is no error.
* Add dataTables exception class.

[7.0] Add server-side error handler.

---

src/Engines/QueryBuilderEngine.php

[7.0] Fix column name added when relation is belongsToMany.

---

src/Processors/DataProcessor.php

Remove array when escaping values.
Fix `htmlspecialchars() expects parameter 1 to be string, array given`.

[7.0] Remove empty array. Fix #1160

---

src/Engines/BaseEngine.php
src/config/datatables.php

- Add support for unescaped unicode in response
- Fix #1034

[7.0] Add config for setting the default JsonResponse header and options.

---

src/Engines/CollectionEngine.php

The Str::lower($value) can not accept array, but sometimes we get array from the client, then exception occurs like:
"error":"Exception Message:\n\nmb_strtolower() expects parameter 1 to be string, array given"

[7.0] The global search keywords should not be an array

---

src/Engines/BaseEngine.php

Type error: Argument 1 passed to App\Transformers\UserTransformer::transform() must be an instance of App\User, array given

[7.0] Fix transformer implementation when parameter requires an object.

---

src/Engines/QueryBuilderEngine.php

you forget to change this getQualifiedOtherKeyName
its not exists in v 5.4

[7.0] Change getQualifiedOtherKeyName

---

src/Datatables.php

[7.0] Use static class to resolve datatables instance.

---

src/Engines/QueryBuilderEngine.php

Bugfix for postgresql having wrong syntax error if column is not text.

[7.0] Add text cast for pgsql regex search

---

src/Engines/BaseEngine.php

Fixed configuration override issue.
Otherwise the databases.php configuration will never take effect.

[7.0] Fixed configuration override issue.

---

phpunit.xml

Hello,
i'm whitelisting src directory in phpunit.xml, because phpunit fails to execute code coverage without it.
i think we should do this on master has well.
thanks.

[7.0] Whitelisting src directory in phpunit.xml

---

src/Processors/DataProcessor.php

Hello,
i'm think this is a bug and not intended.
there is an array_diff_key inside escapeColumns in DataProcessor, but it should be an array_diff i think, because it's the value that matter.
it may be related to https://github.com/yajra/laravel-datatables/issues/1305 and https://github.com/yajra/laravel-datatables/issues/1302
tests are not passing, because they test the old behaviour, so if this gets merged we will need to change the tests.
thanks

[7.0] Fix escapeColumns bug.

---

src/Engines/BaseEngine.php

This PR will:
1. Remove default settings that were extracted to config.
2. Fix merging of default config.
3. Fix config override issue #1293.
NOTE:
Users using the old config file may have to force publish the asset.
`php artisan vendor:publish --tag=datatables --force`

[7.0] Patch configuration override issue.

---

src/Engines/CollectionEngine.php

Fix #1337, sorting on collection relation.

[7.0] Flatten array before comparing then revert to original form.

---

src/Request.php
tests/CollectionEngineTest.php
tests/QueryBuilderEngineTest.php

Validate the key `searchable` in request input against all possible true values `[true, 'true', 1]`

[6.0] Return true for true, true(string) and 1 in isColumnSearchable method

---

src/EloquentDataTable.php

It is useful when you want to add many invisible attributes.
```php
$dataTable->addColumns(['foo', 'a' => 'b'], 3);
```
equals:
```php
$dataTable->addColumn('foo', function ($model) {
return $model->foo;
}, 3);
$dataTable->addColumn('a', function ($model) {
return $model->b;
}, 4);
```

[8.0] Add addColumns() to EloquentDataTable.

---

src/DataTablesServiceProvider.php

`mergeConfigFrom` should be called in the `register` method, it means once the package being registered, its config are ready to use. Then other services can access them safely without caring about the order of application services bootstrap.
This is also mentioned in the [official documentation](https://laravel.com/docs/5.5/packages#configuration):
> To merge the configurations, use the mergeConfigFrom method within your service provider's register method.
`publishes` is useful only in the console application, and in the console application all services will be booted, so it does not matter putting `publishes` whether in `register` or `boot` method. Some core services also put it in `register` to make code organized, such as `MailServiceProvider::registerMarkdownRenderer`.

[8.0] Fix merging config

---

src/DataTablesServiceProvider.php

Fix return type in `provides` function at `DataTablesServiceProvider`

[8.0] Fix return type

---

src/DataTablesServiceProvider.php

The default value of `$defer` is `false`, and this behavior will not be changed ever, so we don't need to override it.
And the `provides()` method is useless for a service provider which is not deferred.

[8.0] Remove unused provides() from service provider.

---

src/Utilities/Helper.php
tests/Unit/HelperTest.php

This PR adds a `wildcardString` method so you can configure the wildcard string. The `wildcardLikeString` method can be used for SQL type queries, but for other plugins a different wildcard then `%` is required.

[8.0] Make wildcard string a function parameter.

---

src/CollectionDataTable.php

When you use:
`Datatables::of(User::all())->toJson()`
In PHP 7.2 you will get:
`PHP Warning:  count(): Parameter must be an array or an object that implements Countable in yajra/laravel-datatables-oracle/src/CollectionDataTable.php on line 69`
This creates an empty array if get request it's not defined so count() doesn't fail.

[8.0] Fix exception/warning for PHP 7.2.

---

src/CollectionDataTable.php

#1466 
Fixed a bug in globalSearch that prevented search results for the value 0.

[8.0] Fix globalSearch not working for 0.

---

src/DataTables.php

Remove unnecessary import. 
PHP Docs
array to PHP 7 compliant

Fix PHP Docs and minor array fixes

---

.styleci.yml

Add styleci checker with Laravel presets.

[8.0] Add styleci cs config.

---

src/helper.php

As discussed in https://github.com/yajra/laravel-datatables/pull/1462#issuecomment-339976815
- Use container binding to resolve DataTables factory
- Support variable length parameters

[8.0] Fix datatables() helper

---

src/Facades/DataTables.php

- Replace `queryBuilder()` to `query()`
- Remove `use` statement  to make it clean

[8.0] Styling phpdoc for facade

---

src/Engines/CollectionEngine.php

I added a fix to take care `mb_strtolower() expects parameter 1 to be string, array given `  error.

[6.0] Fix issue 932

---

src/CollectionDataTable.php
src/Utilities/Helper.php

I've removed the `else`s when we have already returned something :put_litter_in_its_place:
We can also enable `no_useless_else` in `StyleCI`. Should we?

[8.0] Remove useless else statements.

---

src/CollectionDataTable.php
src/DataTableAbstract.php
tests/Integration/QueryEngineTest.php
tests/TestCase.php
tests/Unit/RequestTest.php

After run [`PHPStan`](https://github.com/phpstan/phpstan) up to level 5, some code could get improved in Laravel Datatables :smile:

[8.0] Fixes from PHPStan

---

src/DataTableAbstract.php

After updating to Laravel 5.6, this message is displayed on error (e.g. wrong column name):
Class Illuminate\Contracts\Logging\Log does not exist
As described in the [upgrade guide](https://laravel.com/docs/5.6/upgrade#Logging), `Illuminate\Contracts\Logging\Log` should be changed to `Psr\Log\LoggerInterface`.

Change Log contract to LoggerInterface.

---

src/EloquentDataTable.php

Right now, if the related table uses SoftDeletes, it is not handled via the `performJoin` method.

Check SoftDeletes on HasOne or BelongsTo relations

---

composer.json
src/Utilities/Helper.php

Fixed a bug for "undefined index" errors.
See also https://github.com/yajra/laravel-datatables/issues/1677.

[8.0] Fixed a bug for "undefined index" errors

---

src/DataTableAbstract.php

[8.0] Add support for manual setting of filtered count (#1516)

---

src/DataTableAbstract.php
src/QueryDataTable.php

- Use filteredQuery as callback parameter.
- Fix #1752
```php
return datatables($query)
->with('totalWeight', function($filteredQuery) {
return $filteredQuery->sum('weight');
})
```

[8.0] Fix/Enhance with closure value implementation.

---

src/DataTableAbstract.php

Revert #1758 with callback implementation since its BC.
```php
return datatables($query)
->withQuery('totalWeight', function($filteredQuery) {
return $filteredQuery->sum('weight');
})
```

[8.0] Add withQuery api for query callback.

---

README.md

The provider needs to be quoted, presumably because of the back-slashes that are needed for the namespace.

READEME: publish  command requires quotes

---

src/DataTableAbstract.php
src/Processors/DataProcessor.php

Example `DataTables::of($items)->only(['id', 'name'])->make(true)`

Added ability to pass an array of needed columns and get only them in response, to not add or remove them one by one

---

src/DataTableAbstract.php

DATATABLES_ERROR shouldn't be by default null #1805

---

src/CollectionDataTable.php
src/Processors/DataProcessor.php
src/config/datatables.php
tests/Integration/QueryEngineTest.php

This is a small PR that changes the name of the index column to follow DT syntax.
DT syntax for special columns is like: `DT_NameName`
But the name of the index column was `DT_Name_Name`
I don't know this is a breaking change or no cause I only changed the default value.

[BC] Fix the default name of index column to follow DT syntax.

---

src/QueryDataTable.php
tests/Integration/ApiResourceEngineTest.php
tests/Integration/BelongsToManyRelationTest.php
tests/Integration/BelongsToRelationTest.php
tests/Integration/CollectionDataTableTest.php
tests/Integration/EloquentDataTableTest.php
tests/Integration/HasManyRelationTest.php
tests/Integration/HasOneRelationTest.php
tests/Integration/QueryDataTableTest.php

Add `simplePagination()` api for better performance when using large datasets. Simple pagination will skip the `recordsTotal` count query and will set the value always equal to `recordsFiltered`. 
May address the following performance issues as listed on https://github.com/yajra/laravel-datatables/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aperformance+.
To use, simply add `->simplePagination()` to your dataTables chain method.

[8.0] Add simple pagination api.

---

src/Processors/DataProcessor.php
src/Utilities/Helper.php
src/config/datatables.php

Fixes #1849
P.S. bro I think you need to rewrite whole package again, you use nesting extremely.

[8.0] Only escape callable output of add and edit column.

---

src/Processors/DataProcessor.php
src/Utilities/Helper.php

Reverts yajra/laravel-datatables#1942
Fix #1951

Revert "[8.0] Keep casted attributes #1747"

---

src/QueryDataTable.php

Fixes: https://github.com/yajra/laravel-datatables/issues/1983

[8.0] Keep select bindings option.

---

src/Utilities/Request.php

When dt Request is sent as application/json instead of multipart/form-data
and when in ColumnDef boolean values are used the search does not work. 
Did not work
column[i].searchable = true;
Did work
column[i].searchable = 'true';
But the type of searchable is boolean according to 
https://datatables.net/reference/option/columns.searchable
might affect https://github.com/yajra/laravel-datatables/issues/1789

[8.0] Allow boolean values for column[i].searchable

---

src/Utilities/Helper.php

Fix Issue #2062
Column with blade file is rendered by view() but it cannot be converted to json response. render() will return just HTML code.
Also without render if we try to debug $data inside DT source by Log or var_dump it will result with "Allowed memory size of xxx bytes exhausted".

[9.0] Fix rendering column from blade file.

---

src/EloquentDataTable.php
tests/Integration/QueryDataTableTest.php

A fix for the issue #2045 . It only addresses the "BelongsTo". I did not touch the rest of the relations, so a more complete "fix" can be made.
I also replaced the deprecated function "assertContains" with "assertStringContainsString" in the QueryDataTableTest.
I ran the tests and nothing exploded :P

[9.0] Sorting nested relation that refers to the same table.

---

src/Processors/DataProcessor.php

The `->removeColumn()` function is currently not removing nested Column when using it like this : 
```
$dataTable->removeColumn(‘user.posts’);
```
using the `Arr::forget()` helper enable the use of the dotted notation in this function

[9.0] Enable the dotted notation in the ->removeColumn() function

---

src/CollectionDataTable.php

We had an issue today using DataTables, with server-side processing, using an API to drive the data into the table.
eg...
You have an API that returns 50 records max per request (So we can't simply get it all at once), but provides a "total records" value.
We feed that "total records" into DataTables with `->setTotalRecords($totalRecordsFromApi)`.
This helps us get the correct amount of page numbers for the data.
But whenever we should try to navigate to page 2, telling the API to give us 25 records, starting at offset 25, datatables would just show "No Data".
I initially fixed this by creating `x` dummy rows (x = offset) and merging the collections together before passing the data out to the table, but there must have been a better solution.
We came to the conclusion that an offset …

[9.0] Using predefined offsets for API-driven server-side(ish) DataTables.

---

src/QueryDataTable.php

To prevent UTF-8 error messages in debug mode when queries contain binary data, all texts in the queries part are processed with utf8_encode before adding in to the output.

[9.0] Prevent malformed UTF-8 characters in debug mode.

---

src/DataTableAbstract.php
src/Processors/DataProcessor.php
src/Utilities/Helper.php

When converting the data into an array processable by the library, if the row object is an instance of Arrayable, the method `toArray()` is called on it.
The `toArray()` method compute all getters on the object’s attributes which can take some processing time.
Within this PR, I added the possiblity to use a makeHidden() before this convertion using the following synthax : 
```
$datatable->makeHidden([’posts`]);
```
It can grealty reduce the processing time if you don’t need a huge relationship in the resulting array
As for now, the `makeHidden()` of an eloquent Object does not allow the use of a dot notation (like this `->makeHidden([’posts.comments`]);`) but I hope it will eventually. In the meantime, it might be usefull to implement it inside the laravel-datatables library.

[9.0] Add the possibility to makeHidden() some attribute of a model.

---

src/Processors/DataProcessor.php

The `->only()` function is currently not removing nested Column when using it like this : 
```
$dataTable->only(‘user.posts’);
```
using the `Arr::dot()` helper and then the `Arr::set()` helper enable the use of the dotted notation in this function

[9.0] Enable the dotted notation in the ->only() function

---

src/EloquentDataTable.php
tests/Integration/HasManyRelationTest.php
tests/Integration/HasOneRelationTest.php
tests/Models/Heart.php
tests/Models/Post.php
tests/TestCase.php

Existing method of SoftDelete check brakes relations that looks like:
```
class Thread extends Model {
public function threads() {
return $this->belongsTo(Thread::class)->withTrashed();
}
}
```
or
```
class Thread extends Model {
public function threads() {
return $this->belongsTo(Thread::class)->onlyTrashed();
}
}
```
Both of them got filtered by `whereNull($deletedAt)` while joining. 
Instead of this, no filtering should be applied at all on first model. 
`whereNotNull($deletedAt)` should be called at second model. 
This works well out of a box.

[8.0] Removal of redundant SoftDelete check.

---

src/DataTableAbstract.php
src/QueryDataTable.php
src/Utilities/Config.php
src/config/datatables.php

Fix #2161
```php
->eloquent($query)
->startsWithSearch(); // enable starts with keyword filter.
````

[9.0] Add support for startsWithSearch filter.

---

composer.json
src/CollectionDataTable.php
src/DataTableAbstract.php
src/DataTablesServiceProvider.php
src/Processors/DataProcessor.php
src/Utilities/Helper.php

[9.0] Fix deprecated helper functions, then add support for Laravel 6.

---

src/Engines/CollectionEngine.php

At my place of work we are still using Laravel 5.4 and Laravel Datatables 7. This small change is necessary to prevent us requiring a fork of Laravel Datatables.
Here are the later commits where this problem is fixed in Laravel Datatables 8/9.
- https://github.com/yajra/laravel-datatables/commit/4136d7b
- https://github.com/yajra/laravel-datatables/commit/784fdeb

[7.0] Use an empty array as the default value when no columns are found

---

src/QueryDataTable.php

Fix #2159, #2194.
```php
->eloquent($query)
->orderColumn('status', function($query, $order) {
$query->orderBy('status', $order);
});
```

[9.0] Allow orderColumn using closure.

---

src/QueryDataTable.php

Set filterApplied to true to always trigger counting of filteredRecords.

[9.0] Fix skipTotalRecords api not working on initial state.

---

src/DataTablesServiceProvider.php

Prevents passing `null` to the `foreach` loop in case no database engines defined.
Fix #2202

Cast database engines to array.

---

src/DataTableAbstract.php
src/Processors/DataProcessor.php
src/Utilities/Helper.php

The opposite of PR #2085 
Add a makeVisible() to the row object.
Use case: 
My eloquent model have `$visible` attribute that limit serialization to JSON.
e.g. `protected $visible = ['uuid', 'name'];`
Need a method to temporarily modifying attribute visibility on datatables (on opposite of makeHidden()).

[9.0] Add the possibility to makeVisible() some attribute of a model.

---

src/CollectionDataTable.php

This change fix problem with non-existing variables/attributes during sorting by Collection engine.
There is no problem with displaying undefined values thanks this:
`->columnDefs([['defaultContent' => '-', 'targets' => '_all']])`
But when we try sort column we will get an error:
`Undefined index: resourcename.non_existing_attribute in C:\laragon\www\app\vendor\yajra\laravel-datatables-oracle\src\CollectionDataTable.php:298`

[9.0] Fix issue with non-existing variables/attributes .

---

src/Processors/DataProcessor.php

After the PR #2399 some of our Datatables were not working as expected.
This is because as a row attribute we sometimes pass a `Htmlable` object `HtmlString`.
Like this:
```
public function dataTable($query): DataTableAbstract
{
->eloquent($query)
->setRowClass('cursor-pointer')
->addRowAttr('onclick', fn (Model $model) => new HtmlString("window.location.href = '" . route('blabla') . "';"));
}
```
I just added an extra check to the dataprocessor function escapeRow to see if it is a Htmlable object. So it can be passed to the `e` function where it correctly handles the Htmlable
```
if ($value instanceof Htmlable) {
return $value->toHtml();
}
```

Escape row in data processor also accepts Htmlable 

---

src/CollectionDataTable.php
tests/Integration/CollectionDataTableTest.php

For a `CollectionDataTable`, don't use string comparison functions when sorting two numeric values. A test case is included. Resolves #1934

Use simple numeric sorting when dealing with numeric values

---

src/QueryDataTable.php

Fix https://github.com/yajra/laravel-datatables/issues/1953
Sample Code:
```php
->orderColumn('name', false)
```

Disable ordering via orderColumn.

---

src/CollectionDataTable.php
src/DataTableAbstract.php
src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

Fix #2463, #2471
JS Demo ref: https://editor.datatables.net/examples/extensions/searchPanes.html
```php
$users = User::query()->select('id as value', 'name as label')->get();
$categories = Category::query()->select('id as value', 'name as label')->get();
->eloquent(Post::query())
->searchPane('user_id', $users)
->searchPane('category_id', $categories);
```

[9.0] Add support for search panes.

---

src/Contracts/Formatter.php
src/DataTableAbstract.php
src/Processors/DataProcessor.php
tests/Integration/QueryDataTableTest.php

- Proposed implementation of field/column [formatters](https://editor.datatables.net/manual/php/formatters).
- Fix https://github.com/yajra/laravel-datatables-editor/issues/33
```php
use Carbon\Carbon;
use Yajra\DataTables\Contracts\Formatter;
class DateFormatter implements Formatter
{
protected $format;
public function __construct($format = null)
{
$this->format = $format;
}
public function format($value, $row)
{
if ($this->format) {
return Carbon::parse($value)->format($this->format);
}
return Carbon::parse($value)->diffForHumans();
}
}
```
```php
public function dataTable($query)
{
$formatter = new DateFormatter($format = 'Y-m-d');
->eloquent($query)
->formatColumn('updated_at', new DateFormatter) // using new formatter instance
->formatColumn('created_at', …
```

[9.0] Add column formatter.

---

src/QueryDataTable.php

This PR fixes - will use the builder instance when using eloquent instead of using the base query builder.
Fixes codes like:
```php
->searchPane('tags', $tags, function ($q, $ids) {
return $q->whereHas('tags', function ($q) use ($ids) {
return $q->whereIn('taggables.tag_id', $ids);
});
})
```

Fix builder instance when using eloquent.

---

src/EloquentDataTable.php

Recent PR https://github.com/yajra/laravel-datatables/pull/2580 fails when a multiple level relationship is used ($relation string has several dot separated relations). I've created this fix in order to check only the first relation (I don't really know how Laravel behaves with multi level relationships when all or any are morphed).

Fix morph relation support with multi level relations

---

src/QueryDataTable.php

I discovered a warning in the orderColumn function if you use the closure syntax with Laravel .idea and PHPStorm 2021.1 installed.
Changing the PHPDoc for the function to include \Closure as a type I had no error anymore. I double checked the documentation and here the closure syntax is mentioned:
https://yajrabox.com/docs/laravel-datatables/master/order-column
Because I was in the class anyway I checked my PHPStorm warnings for the class and find 2 other things that can be cleaned up. 
Hope the PR will help

Code cleanup in QueryDataTable class

---

src/QueryDataTable.php
tests/Unit/QueryDataTableTest.php

Hey @yajra,
This time I've added tests so we are sure we don't break anything - to make things testable I had to change the visibility of `prepareCountQuery()` which is now `public`.
This approach utilizes the existing `isComplexQuery()` to determine if we need to wrap the complex query or not.
If we have more examples they should be easy to add now.
Cheers Adrian
---
Fixes #1928

[9.x] Improve count performance for simple queries.

---

src/QueryDataTable.php

vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php
```
protected function showDebugger(array $output)
{
$query_log = $this->connection->getQueryLog();
array_walk_recursive($query_log, function (&$item) {
$item = utf8_encode($item);
});
```
Some fixes:
```
protected function showDebugger(array $output)
{
$query_log = $this->connection->getQueryLog();
array_walk_recursive($query_log, function (&$item) {
if (is_string($item)) {
$item = utf8_encode($item);
}
});
```

Query with subqueries exception fix

---

src/DataTables.php

This allows PHPStan to understand that when you call eloquent it is now dealing with an EloquentDataTable.
Before this change it keeps assuming that it is the DataTableAbstract class and you have to fix it with a useless variable and an @var tag.

Changed PHPDocs to have the most specific class as their super return type

---

src/EloquentDataTable.php
tests/Integration/EloquentDataTableTest.php

The `DataTables::eloquent()` method accepts a `Illuminate\Contracts\Database\Eloquent\Builder` which can be an eloquent builder, but also an eloquent relation.
Using `DataTables::eloquent(User::query())` works fine, but `DataTables::eloquent($user->posts())` throws the following error:
```
Exception Property [columns] does not exist on the Eloquent builder instance. 
vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:1701 Illuminate\Database\Eloquent\Builder::__get
vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php:59 Yajra\DataTables\QueryDataTable::__construct
vendor/yajra/laravel-datatables-oracle/src/EloquentDataTable.php:39 Yajra\DataTables\EloquentDataTable::__construct
vendor/yajra/laravel-datatables-oracle/src/DataTableAbstract.php:167 …
```

Create eloquent datatable from relation

---

src/QueryDataTable.php

[canCreate](https://github.com/yajra/laravel-datatables/blob/master/src/QueryDataTable.php#L85) function at [QueryDataTable](https://github.com/yajra/laravel-datatables/blob/master/src/QueryDataTable.php) should accept `QueryBuilder` only but it accepts `EloquentBuilder`  aslo because `EloquentBuilder` contract extends `QueryBuilder `

[10.x] Make canCreate at QueryDataTable accept QueryBuilder only

---

src/QueryDataTable.php

I have a `customers` table which is related to `customers` via `parentCustomer`.
When I try to search it uses the following expression as the column name:
```sql
LOWER(`customers` as `laravel_reserved_0`.`name`)
```
which clearly doesn't make sense since the table alias should only be added to the `FROM table_name` section of the query.
My code above checks if our "searchable column name with table prefix" has an ` as ` inside and only gets the `table_alias.searchable_column` from it.
BEFORE:
```sql
LOWER(`customers` as `laravel_reserved_0`.`name`)
```
AFTER
```sql
LOWER(`laravel_reserved_0`.`name`)
```

Fixed the search column for same table relations

---

src/CollectionDataTable.php

https://stackoverflow.com/questions/71707325/migration-to-php-8-1-how-to-fix-deprecated-passing-null-to-parameter-error-r#answer-71719307

PHP 8.1 Depreciation Fix

---

composer.json
src/DataTables.php

This allows people to use corresponding method calls like:
```
$builder = datatables()->eloquent($query);
```
instead of needing to use the `make` method.
```
$builder = datatables()->make($query);
```
Since only the `make` is using the classes from `datatables.engines`, the code is not consistent.

Methods pointing to the "uncustomizable" classes.

---

src/QueryDataTable.php

```
'search'         => [
'smart'            => false,
'multi_term'       => false,
'case_insensitive' => true,
'use_wildcards'    => false,
'starts_with'      => true,
],
```
If this is the case, line 449 would return keyword% without converting it to lower case first. The change suggested in this request will first check the sensitivity, convert to lower if set to true, and then return lower("$keyword%").

fix: case insensitive starts with search #2917

---

src/QueryDataTable.php
tests/Integration/CustomOrderTest.php

Following this issue : https://github.com/yajra/laravel-datatables/discussions/2905
When creating custom order for a column with dot notation, 
if the column name was `relation.column` (`user.id`)
AND the relationship was eagerloaded, 
the default order would be `relation_table.column` (`users.id`)
BUT if we would customise the order of that column like that : 
```
->orderColumn('user.id', function ($query, $order) {
// For testing purposes, revert the order
$query->orderBy('users.id', $order == 'desc' ? 'asc' : 'desc');
})
```
the custom order would not be applied
by checking if a custom order exists for our column definition name, we fix that behavior

fix: Custom Order on eager loaded relationships was not working

---

src/ApiResourceDataTable.php

Fixes #2943 
Issue seems to be due to an extra layer of properties when converting a resource to a collection.
Normal Collection :
Converted Resource Collection :

fix: Fix anonymous resource collection data formatting

---

src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

To reduce the processing made by the count on the filtered query, I performed a check if the query has been altered after the initial query
It will improve performance on the first call to a DataTable (as no filter has been applied yet, and any subsequent request without a search)
I had to modify some assertions in the tests as the filteredRecords should never be greater than the totalRecords.
fixes #2959

Prevent the filteredCount() query if no filter is applied to the initial query

---

src/QueryDataTable.php
tests/Unit/QueryDataTableTest.php

When performing subqueries, some of the keywords used to determine if a query is complexe can be found in subqueries inside the main query : 
```
protected function isComplexQuery($query): bool
{
return Str::contains(Str::lower($query->toSql()), ['union', 'having', 'distinct', 'order by', 'group by']);
}
```
For exemple : 
```sql
select 
"users".*,
(select id from posts where posts.user_id = users.id order by created_at desc limit 1) as last_post_id
from "users"
```
This query was detected as complexe, but the subquery had no impact on the number of records returns, 
The subquery was executed and had a huge impact on performance
To force this behavior, you can use the `ignoreSelectsInCountQuery()` on a QueryDatatable : 
```php
$dataTable = app('datatables')->of(
DB::table('users') …
```

feat: Optimize countQuery with complex select

---

src/DataTableAbstract.php
tests/Integration/QueryDataTableTest.php

To match the behavior of the filterColumn in globalSearch where only the displayed columns are searched, I propose the following : 
Example : a POST Datatable
When doing this 
```php
->editColumn('user.name', function ($post) {
return "<a href='/users/{$post->user->id}'>{$post->user->name}</a>";
})
```
If you want to reuse this Datatable on the User page, you would probably do this : 
```php
$columns = [
'user.name' => ['title' => 'Author'],
'title' => ['title' => 'Post Title'],
'comments_count' => ['title' => '#Comments'],
];
if($this->user){
array_forget($columns, 'user.name');
}
```
and in your query, you don't need to eagerload the user when already in contexte : 
```
Post::query()
->withCount('comments')
->when(!$this->user, function($query){
$query->with('user:id,name');
});
``` …

feat: Prevent editColumn when column is not shown

---

src/EloquentDataTable.php
src/QueryDataTable.php

#3010 
The query `Grammar` is required to stringify the expression. This ends up needing to be changed in both files as the `AbstractDataTable` does not have access to a connection to retrieve the grammar.

#3010 - convert expressions to strings

---

src/EloquentDataTable.php
tests/Integration/DeepRelationTest.php

So the idea is that we have `Post -> belongsTo -> User -> belongsToMany -> Role` relationships.
Currently when we enter the following column data:
```
[
'data' => 'user.roles.role', 
'name' => 'user.roles.role', 
'searchable' => 'true',
'orderable' => 'true',
],
```
We get an error `roles.role` column not found, since it only checks for 1 relation, which is the `user` relation in out case.
From now on if there are more than 1 `.` character it will check the other relation as a nested `whereHas` clouse

feat: Ability to use deep relations for searching

---

src/DataTableAbstract.php
src/Processors/DataProcessor.php
src/Utilities/Helper.php
src/config/datatables.php
tests/Integration/IgnoreGettersTest.php
tests/Models/User.php
tests/TestCase.php

The issue was when a model have a getter overwriting an existing attribute in the database (See the new User Migration and User Model)
we have now a "color" column and a getColorAttribute() which override the value if null.
For simplicity, in the test, there is no real issue with it, but if you have this type of getter (poor code quality, but it is for the sake of the example): 
```php
public function getColorAttribute(){
return $this->posts->count() ? '#000000' : '#ff0000'
}
```
with this query : 
```php
User::select('users.*')
```
This would result in a n+1 as every User row will call this getter and make a query to the posts table for each row
Facing this issue, you have multiple solution : 
Eager loading your posts (even if not needing it): 
```php …
```

feat: add ability to disable eloquent getter mutator

---

src/QueryDataTable.php

This is a very important update for advanced customizations.
I currently have a `footer` method on some of my datatables which allows me to query the datatable and sum up the rows via PHP.
```php
public function footer(): array
{
request()->offsetUnset('order');
$results = $this->ajaxBase()
// if filtering is needed
// ->filter($this->getFilter(), true)
->skipPaging()
->prepareQuery()
->results();
$footer = [
'footer_col_1' => 0,
'footer_col_2' => 0,
];
foreach ($results as $result) {
$footer['footer_col_1'] += $result->col_1;
$footer['footer_col_2'] += $result->col_2;
}
return $footer;
}
```

feat: convert prepareQuery from protected to public

---

src/Utilities/Helper.php

Usage:
```php
$builder->editColumn('permissions_display', [
'admin.roles.data-table.permissions-display', ['groupedPermissions' => $groupedPermissions],
]);
```
I couldn't decide if I should make it an associative array or not, but this seems simple enough. If the `$content` is an array get the split it and add the second value to its view data.
Extremely straightforward code for mini extra function.
```php
if (is_array($content)) {
[$view, $viewData] = $content;
return static::compileBlade($view, static::getMixedValue($data, $param)  + $viewData);
}
```

feat: Ability to pass static data to a blade render

---

src/DataTableAbstract.php
tests/Integration/EloquentDataTableTest.php

The PR will allow formatColumn to use a closure. The exception was also removed and will fall back to the original column value instead.
```php
->formatColumn('created_at', fn($value, $row) => Carbon::parse($value)->format('m/d/Y'))
```

feat: allow closure on formatColumn

---

composer.json
src/CollectionDataTable.php
src/DataTableAbstract.php
src/QueryDataTable.php

Fixes #3077 
@yajra
What do you think? Feel free to let me know if i should change some parts.
**disableOrdering js script**: We could either integrate that into laravel-datatables-html or add it into some docs for people to implement on their own (if they want to). I could also leave that part out completely. What do you think?
If it's possible to somehow add custom scss/js code into laravel-datatables-html i would also do 2 more pull requests for nice optimizations that i'm using since a long time on my own projects.
Also it would be good to add an example usage into docs:
```php
public function dataTable(QueryBuilder $query): EloquentDataTable
{
return (new EloquentDataTable($query))
// Enable scout search for eloquent model
->enableScoutSearch(Product::class)
// Add filters to scout …
```

feat: Scout Search Implementation

---

src/QueryDataTable.php

This PR will fix error when PHP extension `iconv` not enabled, so we can't use function `iconv()`.
```
Call to undefined function Yajra\DataTables\iconv()
{"userId":1,"exception":"[object] (Error(code: 0): Call to undefined function Yajra\\DataTables\\iconv() 
at .../vendor/yajra/laravel-datatables-oracle/src/QueryDataTable.php:867)
```

fix: Prevent error when PHP extension iconv not enabled.

---

src/QueryDataTable.php

Hi !
Here is a optimization for scout search (if smart search is enabled).
Old: keyword is exploded using spaces into multiple keywords and then each keyword gets scout-searched
New: whole keyword gets scout-searched (without exploding), the search engine deals with multiple words

fix: scout search with smart search

---

src/QueryDataTable.php
tests/Unit/QueryDataTableTest.php

The issues was for simple queries with complexe wheres, a sub query was used resulting in the following query : 
```sql
select count(*)
from (select "users".*
from "users"
where (select "title"
from "posts"
where "posts"."user_id" = "users"."id"
order by "created_at" asc
) = ?
) count_row_table
```
resulting into an uneccessary temporary table, the query we would like to have would be this one : 
```sql
select count(*)
from "users"
where (select "title"
from "posts"
where "posts"."user_id" = "users"."id"
order by "created_at" asc
) = ?
```
On our app, the gains were massive, one of our datables would just timeout and with this change it load now in less than 5 seconds

feat: Optimize simple queries

---

src/QueryDataTable.php

Laravel 11 introduced a mariadb database driver. We can use the same code as for mysql.

fix: mariadb support for scout search

---

src/Utilities/Request.php

In most cases, the `dir` attribute is empty (null) which causes a notice error in the recent PHP version.
> ErrorException: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/vendor/yajra/laravel-datatables-oracle/src/Utilities/Request.php:101

fix: ErrorException when direction is null

---

src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

Hi, we always use `setTotalRecords(0)` since we only show the filtered records count. After upgrading to Laravel 11 we noticed that our pagination stopped working. This seems to be caused by c37494f11f0b6e198fa7428edd38e5d5b2a6d9de. This PR changes the logic to always query the filtered count if the total count was set manually.

fix: make query for filteredRecords when totalRecords was manually set

---

src/Utilities/Helper.php

Resolves #3156 and lets the transformer deal with date formatting as intended.

Ensure dates are not turned to arrays by processor

---

src/DataTableAbstract.php
src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

This PR undoes the deprecation of `skipTotalRecords` and restores the working of `setTotalRecords(0)` back to how it was in [v10.4.3](https://github.com/yajra/laravel-datatables/releases/tag/v10.4.3).
Alternative to #3169.
Partially reverts #3157.

Add skip total records back

---

README.md

docs: quick installation

---

.gitattributes
.github/workflows/continuous-integration.yml
.github/workflows/pint.yml
.github/workflows/static-analysis.yml
.styleci.yml
phpstan.neon.dist
sonar-project.properties
src/Contracts/DataTable.php
src/QueryDataTable.php
src/config/datatables.php

- ci: add PHP 8.4
- ci: fix Pint workflow
- ci: remove styleci
- chore: update export ignore
- fix: static analysis
> Error: Method Yajra\DataTables\QueryDataTable::results() should return Illuminate\Support\Collection<int, array> but returns Illuminate\Support\Collection<int, stdClass>.

fix: static analysis

---

README.md
composer.json

Laravel v12 Compatibility

---

src/DataTableAbstract.php
src/QueryDataTable.php

I created a custom action where I need to return a json with complex manipulation on the data.
In that action I need to access the query results.
This is an improvement to prevent the query to be triggered twice.

fix: misc improvements

---

src/EloquentDataTable.php
src/QueryDataTable.php

Alternative to https://github.com/yajra/laravel-datatables/pull/3228
Not sure which implementation is better, I will let you choose what you prefer.
I would like to suggest to add resolveRelationColumn() as new param to the filter callbacks:
```php
$datatable = new EloquentDataTable($query);
$datatable
->filter(function ($query, $scoutSearch, $resolver) {
// $resolver automatically create joins if needed
$query->where($resolver('foo.bar'), 'xxx');
})
->filterColumn('foo.bar', function ($query, $keyword, $resolver) {
// $resolver automatically create joins if needed
$query->where($resolver('foo.bar'), 'xxx');
})
;
```

feat: add relation resolver param to filter callbacks

---

src/EloquentDataTable.php
src/QueryDataTable.php

When using complex queries with joins, I am often facing ambiguous column name errors when sorting a column of the base table sharing the same name as a column of a relation table field (eg: created_at)
Until now, the workaround I used was to rename my columns
``` php
// From
DateColumn::make('created_at')`
// To
DateColumn::make('created_at', 'table.created_at')
```
But it's probably better to fix the root cause by forcing the table name if the column is not a relation.
And it's consistent with `$this->joinEagerLoadedColumn()` which is returning columns name with alias.

fix: prevent ambiguous column names

---

src/QueryDataTable.php

Fixes https://github.com/yajra/laravel-datatables/issues/3235
This PR improves detection of column aliases.
Before, it could detect only if the alias has exactly 1 space between `as` and alias name.
Now it supports (I hope) all cases:
```php
DB::raw('table.column as   alias'); // multiple spaces
DB::raw('table.column as `alias`'); // escaped (wrapped) aliases
DB::raw('table.column as alias, table.column2 as alias2'); // multiple aliases in 1 definition
// multiple lines
DB::raw('table.column as  
alias');
```

fix: improve column alias detection

---

src/QueryDataTable.php
tests/Integration/CustomOrderTest.php

Same as https://github.com/yajra/laravel-datatables/pull/3229 but for `orderColumn()`
In https://github.com/yajra/laravel-datatables/pull/3216, I added the `$column` parameter to pass the current column alias to the order callback function, but this is not really helpful when we want to work on other columns as reported by @Arkhas.
So I decided to replace this param by the resolver in the same way as `filterColumn()`
```php
$datatable = new EloquentDataTable($query);
$datatable
->orderColumn('foo.bar', function ($query, $order, $resolver) {
// $resolver automatically create joins if needed
$query->orderBy($resolver('foo.bar'), $order);
// or
$query->orderBy(DB::raw("{$resolver('foo.amount')} * {$resolver('foo.quantity')}"), $order);
})
;
```

feat: add relation resolver param to order callback

---

src/QueryDataTable.php

Fixes https://github.com/yajra/laravel-datatables/issues/3237
In the previous implementation, I was looking only for prefixed columns.
Unfortunately, this was not working as expected when custom select without alias were manually added.
I have refactored to try to retrieve the table prefix by searching in all selected columns even if they do not have an alias.

fix: improve prefix detection

---

src/EloquentDataTable.php

In https://github.com/yajra/laravel-datatables/pull/3216, I implemented automatic unique aliases on relation tables to prevent duplicated table name issues.
That bugfix unfortunately introduce a BC break that we cannot prevent.
As [suggested](https://github.com/yajra/laravel-datatables/pull/3216#issuecomment-2853852152) by @Arkhas, that makes that feature optional and disabled by default to keep backward compatibility.
```php
$datatable = new EloquentDataTable($this->query());
$datatable->enableEagerJoinAliases();
```

feat: add option to enable alias on relation tables

---

src/EloquentDataTable.php

See https://datatables.net/reference/option/columns.data#string
It's possible to specify the separator of array values inside the brackets: `name[, ]`
Before this patch, only `name[]` was working.

fix: support for array notation

---

src/CollectionDataTable.php
src/DataTableAbstract.php
src/QueryDataTable.php
tests/Integration/MinSearchLengthDataTableTest.php

fix: #3241
```php
public function dataTable(QueryBuilder $query): EloquentDataTable
{
return (new EloquentDataTable($query))
->minSearchLength(5)
->setRowId('id');
}
```
```json
{
"draw": 2,
"recordsTotal": 0,
"recordsFiltered": 0,
"data": [],
"error": "Exception Message:\n\nPlease enter at least 5 characters to search."
}
```

feat: add min search length control

---

src/QueryDataTable.php

The orderColumn() method in QueryDataTable is documented and intended for public use (as shown in package docs), but was incorrectly marked as @internal. This caused static analyzers like PHPStan to report false positives when calling the method in userland code.
Removing the @internal annotation clarifies that orderColumn() is part of the public API.

fix: remove @internal annotation from orderColumn() method

---

src/Utilities/Helper.php

This PR improves the `Helper::compileBlade` method by replacing the use of `eval()` with the safer and Laravel-native `Blade::render()` method.
- Removed the `eval()` approach to compile Blade strings.
- Added `Blade::render($str, $data)` for string compilation.
- Maintains existing functionality while improving security and maintainability.
- ✅ Safer: Eliminates potential security risks from `eval()`.
- ✅ Cleaner: Uses Laravel's built-in Blade rendering.
- ✅ More maintainable and testable code.
- No behavioral changes for existing functionality.
- Fully backward compatible.

Replace unsafe eval() with Blade::render() in Helper::compileBlade

---

src/Utilities/Request.php

This PR introduces the `__isset()` magic method to the `Request` class, enabling attribute existence checks similar to how `__get()` retrieves attributes.
- Added `__isset(string $name): bool` method to `Request.php`.
- Delegates existence checking to the base `request()` instance.
```php
/**
* Determine if an attribute exists on the base request.
*
* @param  string  $name
*/
public function __isset($name): bool
{
return isset(request()->$name);
}
```
- ✅ Provides a consistent way to check if a request attribute is set.
- ✅ Improves developer experience when working with dynamic request properties.
- ✅ Keeps behavior aligned with the existing `__get()` method.
- Backward compatible — no breaking changes introduced.
- Complements existing request property access patterns.

Add __isset() method to Request class for attribute existence check
