yajra/laravel-datatables

src/yajra/Datatables/Engine/BaseEngine.php

in php
empty('0') == true
so,when search a field value with '0',this function did not work;

fix a bug with  search value is '0'

---

src/yajra/Datatables/Engines/QueryBuilderEngine.php
src/yajra/Datatables/Request.php

Thanks for this great package !
Here is a little patch to add regular expressions search on columns.

Add support for regular expressions in column search

---

src/yajra/Datatables/Engines/BaseEngine.php

Check if we need to pass array or the object to transformer

Pass object or array to transformer

---

src/yajra/Datatables/Engines/BaseEngine.php

issue url
https://github.com/yajra/laravel-datatables/issues/157

the proper way to fix addColumn Bug

---

src/yajra/Datatables/Engines/QueryBuilderEngine.php

in firebird, it's important to wrap the alias

use connection grammar to wrap the row_count alias

---

src/yajra/Datatables/Datatables.php

"select distinct '1' as row_count" always made count = 1

count method needs to check for distinct as well as union

---

src/Services/DataTable.php

Added column selection for print preview.
Hopefully I did it right this time =P

Update DataTable.php printPreview

---

src/yajra/Datatables/Engines/QueryBuilderEngine.php

use query->leftJoin in datatables

---

src/yajra/Datatables/Request.php

but another bug is :i search quickly，the datatables will let my user auth logout, what happen?

use select one column, one column one search 

---

src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php
src/Engines/QueryBuilderEngine.php

PR for discussing issue https://github.com/yajra/laravel-datatables/issues/333

Issue #333

---

src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php
src/Engines/QueryBuilderEngine.php

[6.0] Add feature to override default ordering via order method.

---

src/Engines/QueryBuilderEngine.php

The column name should be stated as
`name: relation.column_name`

Global search on eager loaded models

---

src/Engines/QueryBuilderEngine.php

Add missing doc block.

---

src/Helper.php

Fix string casting for object values.

Fix string casting for object values.

---

src/DatatablesServiceProvider.php
src/Facades/Datatables.php

[Proposal] Re-implement facade.

---

src/Html/Builder.php

Hi,
Just a nice addon. allows the user to pass a column instance for in case I would like to mess with it on my own instead of using the basics.
Vlad.

Allows passing instance of Column into Builder columns

---

src/Html/Column.php

Hi,
This allows the user to pass parameters to column render.
For views and closures.
Vlad.

Adds an option to pass parameters to column render

---

src/Datatables.php

Fix namespace conflict that can occur when using other packages having their own implementation of DataTables (like the pragmarx/tracker package).
Fixes Issue #464

Use detailed namespace in app() helper

---

src/Engines/QueryBuilderEngine.php

This PR will fix eager loading column search where related tables are not being joined automatically.
Fixes issue #443.

Fix eager loading column search. Fix issue #443

---

src/Engines/BaseEngine.php

Add callable type content parameter.

Patch phpdoc to fix #531

---

src/Engines/QueryBuilderEngine.php

This PR will fix issue #461 where ordering fails when relation is belongsToMany.

Fix eager loading ordering for belongsToMany relationship. Fix #461

---

src/Html/Builder.php
tests/HtmlBuilderTest.php

Add support for responsive extension. Fix #526

Add support for responsive extension. Fix #526

---

src/Engines/BaseEngine.php

Use Str class helper instead of strlen.

---

src/Engines/QueryBuilderEngine.php

Reference:
http://tracker.firebirdsql.org/browse/CORE-3559

Add CAST for Firebird

---

src/Services/DataTable.php
src/resources/assets/buttons.server-side.js

This PR will add an `export` button which are a collection of `csv, xls & pdf` button.

Add export button collection.

---

src/Services/DataTable.php

Fix default print preview view path.

Fix default print preview view path.

---

src/resources/views/print.blade.php

Remove media screen to fix styles when printing.

Remove media screen to fix styles when printing.

---

src/Engines/QueryBuilderEngine.php

Fix column wrapping when smart search is disable.

Fix column wrapping when smart search is disable.

---

src/Engines/QueryBuilderEngine.php

This PR fixes searching depending on configurations:
- Smart search
- Case insensitive search
- Wildcard search
This also fixes configuration based searching on related models.

Fix searching based on configurations.

---

src/Html/Builder.php

Example usage:
```php
public function html()
{
return $this->builder()
->ajax([
'url'  => '',
'data' => 'function(d) {d.range = $("#range").val()}',
]);
}
```

Add support for ajax data function.

---

src/Engines/BaseEngine.php
src/Html/Builder.php
src/Processors/DataProcessor.php

An Index-Column is useful when users need to reference to what they see
on screen while working with others.

Added Auto-Index Column.

---

src/DatatablesServiceProvider.php
src/Engines/BaseEngine.php
src/config/config.php

Decouple Fractal for better integration which will help address issue like #633. To extend, just use the IoC `app('datatables.fractal')`.

Decouple fractal for better integration.

---

src/Engines/QueryBuilderEngine.php

Fix double percent sign in query. Fix #665. Replacement for #677.

Fix double percent sign in query. Fix #665

---

composer.json

Use dompdf v0.7.x.

---

src/Engines/CollectionEngine.php

Implement setTotalRecords on collection engine.
Addresses #702 and #703.

Implement setTotalRecords on collection engine.

---

src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php

Issue #706: Fix paging

---

src/Engines/QueryBuilderEngine.php

Fix eager loaded model searching function.

---

src/Services/DataTable.php
src/config/config.php

This PR will:
- Make snappy pdf generation configurable via `datatables` config file.
- Fix loading of printPreview using loadHTML.

Make snappy pdf generation configurable via datatables config file.

---

src/Engines/QueryBuilderEngine.php

This PR will:
* Refactor HasOneOrMany as suggested in https://github.com/yajra/laravel-datatables/pull/733#issuecomment-252952070
* Fix cs and rearrange methods.

Refactor HasOneOrMany and fix cs.

---

composer.json

Update league/fractal version to ~0.14. Fix PR implementation #738. Credits to @tyloo

Update fractal to ~0.14. Fix #738.

---

src/Engines/QueryBuilderEngine.php

Adding support for morphToMany to search

support to morphToMany

---

src/Engines/QueryBuilderEngine.php

Tested on Laravel5.2 with Datatables v6.21.1.
This will make search on nested relation can work properly.
Reference issue: #696 
Code on PSR2 style. Validated by PHPCS.
I add all comments in my code as much as possible.

[7.0] Make compileRelationSearch support nested relations.

---

src/Engines/QueryBuilderEngine.php

[6.0] Support nested search #841

---

src/Engines/QueryBuilderEngine.php
src/Request.php

Patch request class and use input array access to get the values.
Fix **Error 500 Illegal string offset** issues: #857, #657, #395

Patch request class and use input array access to get the values.

---

src/Engines/QueryBuilderEngine.php

Get the right column for soft delete via Laravel model method.

Custom soft delete column support

---

src/Engines/QueryBuilderEngine.php

Fix adding of table prefix before casting the column.

---

src/Engines/QueryBuilderEngine.php

Fix double wrapping of column name.

---

src/Engines/BaseEngine.php

Support for UTF8 characters when creating wildcard query

---

src/Engines/QueryBuilderEngine.php

- Fix #927.
- Possible fix for #873

Do not append table name if instance is expression.

---

src/Html/Builder.php

It allows me to use `->pipeline('url/to/ajax', 5)`.
<!--
Thanks for the Pull Request!  Before you submit the PR, please
look over this checklist:
- Have you read the [Contributing Guidelines](https://github.com/yajra/laravel-datatables/blob/master/.github/CONTRIBUTING.md)?
Yes.

Datatables Pipeline Plugin support (Basic)

---

src/Datatables.php
tests/CollectionEngineTest.php
tests/DatatablesTest.php
tests/QueryBuilderEngineTest.php

- Revert getHtmlBuilder method for backward compatibility.
- Add html builder test.
- Rename Test class name.

[7.0] Revert Html builder for backward compatibility.

---

src/Engines/QueryBuilderEngine.php

[7.0] Add bindings from relation.

---

composer.json

[7.0] Use stable packages versions.

---

src/Engines/QueryBuilderEngine.php

Implementation from PR #962 to fix #960 .

[6.0] Add bindings from relations.

---

src/Engines/CollectionEngine.php
tests/Integration/CollectionEngineTest.php

[7.0] Fix SORT_FLAG_CASE when ordering collection.

---

src/Engines/CollectionEngine.php

[6.0] Fix SORT_FLAG_CASE when ordering collection.

---

src/Engines/BaseEngine.php

Hello,
i was reading the code, and i found a little copy/paste typo.

Minor comment correction

---

composer.json

Might be the reasons for the following issues: #1001, #977

Move orchestra/testbench to require-dev.

---

src/Engines/QueryBuilderEngine.php

[6.0] Add support ordering when search in nested relations.

---

src/Datatables.php
src/Services/DataTable.php

Add a fluent way to send route variables to DataTable service class.
Fix #1069.

[6.0] Fluent variables for service class.

---

src/Services/DataTable.php
src/Transformers/DataTransformer.php

Following the feature request: #1070

[6.0] Display url and A balise as hyperlink in excel export

---

src/Engines/QueryBuilderEngine.php

This pr tries to solve the smart search feature #1109 . The idea for the requested change is from my colleague.
if this solution is preferable I'd also try to implement smart search for the collection engine.

[7.0] Implement multi-term smart search in QueryBuilderEngine.

---

src/Engines/CollectionEngine.php

[7.0] Implement multi-term smart search in collection engine.

---

README.md

Small changes in README.md

---

src/Processors/DataProcessor.php

[7.0] Fix rawColumns not working on relationships.

---

CHANGELOG.md
README.md

Add docs for know php artisan serve bug.

Artisan serve bug docs.

---

src/Engines/BaseEngine.php
src/Engines/QueryBuilderEngine.php

The function **addColumn()** would throw an exception if the newly added column name can not be found in MySQL table and the query still contains the column added by **addColumn( )**. 
So I just add the new column in the blacklist, and it works.

bug fixed: addColumn()

---

src/Engines/QueryBuilderEngine.php
tests/Integration/QueryBuilderEngineTest.php

In relation to PR #1158.
- Fix CS
- Refactor addColumn
- Add tests.

[7.0] Allow filtering of added column if a custom handler was defined.

---

tests/Integration/BelongsToManyRelationTest.php
tests/Integration/BelongsToRelationTest.php
tests/Integration/CollectionEngineTest.php
tests/Integration/EloquentEngineTest.php
tests/Integration/HasManyRelationTest.php
tests/Integration/HasOneRelationTest.php
tests/Integration/QueryBuilderEngineTest.php
tests/Models/Heart.php
tests/Models/Post.php
tests/Models/Role.php
tests/Models/User.php
tests/TestCase.php

- Add eloquent relations tests.
- Add index column test.
- Add multiple term search test.

[7.0] Add more tests.

---

src/Engines/BaseEngine.php
src/config/config.php

- Fix #1034
- Need to update tests

[6.0] Add config for setting the default JsonResponse header and options. 

---

src/Engines/QueryBuilderEngine.php

[7.0] Allow sorting for blacklisted columns with custom handler.

---

src/Engines/BaseEngine.php
src/config/datatables.php

- Extract columns definition to config as suggested on #1144 
- Fix CS

[7.0] Extract columns definition to config.

---

src/Request.php

In relation to https://github.com/yajra/laravel-datatables-html/pull/13.

[7.0] Set columns orderable & searchable property as true by default.

---

src/Contracts/DataTableEngineContract.php
src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php
src/Engines/QueryBuilderEngine.php
tests/Integration/CollectionEngineTest.php

- Refactor make & render method.
- Fix #694, #1229, #1142

[7.0] Process and transform data first before filtering and ordering collection

---

src/Engines/BaseEngine.php

- This PR will fix merging of column definition with config and manually set attributes.
- Fix issue where rawColumns and being skipped.

[7.0] Fix merging of column definitions.

---

src/Engines/CollectionEngine.php

[7.0] Fix multi-column sort of collection. Fix #1237

---

src/Engines/BaseEngine.php
src/Engines/CollectionEngine.php
src/Engines/QueryBuilderEngine.php

Refactor filtering methods.
Fix #1223

[7.0] Fix searching not triggered with zero value.

---

src/Engines/CollectionEngine.php

[7.0] Revert transformed DT_Row_Index back to it's original values.

---

README.md

"--provider" wiil prevent you from accidentally publishing content from other service providers

Readme: implictly set "--provider" when publishing

---

src/Engines/QueryBuilderEngine.php

[7.0] Fix duplicate queries when transforming the output.

---

src/Engines/BaseEngine.php

Possible fix for issues #1301, #1302, #1268

[7.0] Merge array recursive.

---

src/Engines/BaseEngine.php

Use array_replace_recursive:
https://jontai.me/blog/2011/12/array_merge_recursive-vs-array_replace_recursive/
Fix XSS related issues: #1307, #1305, #1306, #1302

[7.0] Fix fetching of column definitions.

---

src/Engines/QueryBuilderEngine.php

Disable offset pagination using limit with additional where clause.
Fix #1332
https://stackoverflow.com/questions/4481388/why-does-mysql-higher-limit-offset-slow-the-query-down
https://stackoverflow.com/questions/8467104/limit-with-offset-limit-500000-10-is-slow-even-after-index?noredirect=1&lq=1
```php
return Datatables::eloquent(User::query())
->limit(function ($query) {
$query->where('id', '>', request('start'));
})
->setTotalRecords(100)
->make(true);
```

[7.0] Add limit query callback method.

---

src/EloquentDataTable.php
tests/Integration/EloquentJoinTest.php

[8.0] Do not resolve column if relation is not eager loaded.

---

src/QueryDataTable.php

Remove void return type. Fix #1367 
Fix PHP 7.0 compatibility.

[8.0] Remove void return type. Fix #1367

---

src/CollectionDataTable.php
src/DataTableAbstract.php
src/DataTables.php
src/DataTablesServiceProvider.php
src/QueryDataTable.php
src/Utilities/Helper.php
src/Utilities/Request.php
src/helper.php
src/lumen.php

[8.0] Fix compatibility with Lumen.

---

src/DataTableAbstract.php

[8.0] Fix return type of fractal integration method annotation.

---

README.md

Change "action" reference in README to "actions"

---

README.md

Hey,
I noticed that the API reference link was broken, so I've updated it!

(fix): Update API link

---

CHANGELOG.md

Use standard date format for changelog.
Add links to compare versions.
Add unreleased section.

[8.0] Fix changelog links.

---

src/Facades/DataTables.php

Methods are static for facade. IDE needs to read it

[8.0] Fix method annotations.

---

src/QueryDataTable.php

recordsFiltered count value wrong when using filterColumn method

[8.0] Fix filtered records total when using filterColumn.

---

src/CollectionDataTable.php
src/DataTablesServiceProvider.php

Add periods for descriptions - PHP Docs

Fix PHP Docs

---

README.md

[Docs] Use query() on quick snippet.

---

tests/TestCase.php

Follow [PHP PSR-2](http://www.php-fig.org/psr/psr-2/#overview)

Update TestCase with PSR-2

---

.styleci.yml

As sugested in #1553 , I've enabled [`no_useless_else`](https://styleci.readme.io/docs/fixers#section-no_useless_else) in `StyleCI`.

[8.0] Enable no_useless_else

---

composer.json

Added Laravel 5.6 Support

---

src/EloquentDataTable.php

Fix ambiguous column 'deleted_at'.

---

src/Helper.php

Fixed a bug for "undefined index" errors

[7.0] Fixed a bug for "undefined index" errors.

---

src/QueryDataTable.php

[8.0] Reset select bindings for count query

---

src/QueryDataTable.php

Reverts yajra/laravel-datatables#1737
Fix #1739

Revert "[8.0] Classify join statements as a complex query."

---

src/Utilities/Request.php
tests/Unit/RequestTest.php

Prevents SQL injection on order direction.

[8.0] Add validation for order direction.

---

src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

Removed simplePagination #1911 as it is still safe atm. Sorry if not, got too excited :) 
To use, simply add `->skipTotalRecords()` to your dataTables chain method.

[8.0] Use skipTotalRecords as it better describe what the function does.

---

src/Processors/DataProcessor.php

Reverts yajra/laravel-datatables#1915

Revert "Fix adding of index column."

---

src/Processors/DataProcessor.php
src/Utilities/Helper.php
src/config/datatables.php

Reverts yajra/laravel-datatables#1852

Revert "[8.0] Only escape callable output of add and edit column."

---

src/Processors/DataProcessor.php
src/Utilities/Helper.php

[8.0] Keep casted attributes #1747

---

src/EloquentDataTable.php

Revert #2051 support for self joins until fix for #2058 soft deletes are applied too.

Revert #2051, fix #2058.

---

src/CollectionDataTable.php
src/QueryDataTable.php

[9.0] Consider black listed columns on column search.

---

src/QueryDataTable.php

[9.]0 Allow column search on blacklisted columns with custom filter.

---

src/QueryDataTable.php
src/config/datatables.php

Add string replace option for column and direction.
Fix #1822, #1738

[9.0] Improve orderByNullsLast SQL generation.

---

README.md

Based on commit https://github.com/yajra/laravel-datatables/commit/d8a965ab91662216956288cafcc4c60306af7b3f#diff-04c6e90faac2675aa89e2176d2eec7d8
I updated readme.md to show that it is compatible with Laravel 6.x to avoid confusion to new users.

[docs] Compatible with Laravel 6.x.

---

README.md

New starter docs for Laravel 6.

[docs] Add link to new quick starter docs.

---

src/EloquentDataTable.php
tests/Integration/HasOneThroughTest.php
tests/Models/Post.php

This pull request add support for HasOneThrough relationship.
I hope I did it well since I'm not fluent at all with that kind of Laravel relation.
However, it sounds working well into my project ^^'

feat(relations): add support for HasOneThrough

---

src/Processors/DataProcessor.php

due to #1975 , #1747 
Instead of escaping all values of row we should escape only strings.

Fix type casting issue

---

README.md
composer.json

Sept 8 is release of laravel 8,

Preparation for laravel 8 support

---

README.md

Add laravel 8 on version compatibility matrix.

Fix laravel version & badge.

---

README.md

"Register provider and facade" is optional in 5.5 and newer

---

LICENSE.md

There were already changes in 2020, so the year should be updated.

Update license to 2020

---

composer.json

PHP8 is released, and laravel also supported it,  let's this plugin too..
ref: https://blog.laravel.com/laravel-php-8-support

PHP8 support

---

src/DataTableAbstract.php

This pull request adds the possibility to change the multi_term search on runtime.
See https://github.com/yajra/laravel-datatables/issues/2575

Add set multi term on runtime

---

src/EloquentDataTable.php
tests/Integration/MorphToRelationTest.php
tests/Models/AnimalUser.php
tests/Models/HumanUser.php
tests/Models/User.php
tests/TestCase.php

make eloquent queries based on polymorphic structure searchable.
This partially address #2573

feat(relations): add partial polymorphic support

---

src/EloquentDataTable.php

Snippet from https://github.com/yajra/laravel-datatables/pull/2587

Add method exists check taken from #2587.

---

src/QueryDataTable.php

[9.x] Remove unnecessary wrap to avoid performance issues

---

src/QueryDataTable.php

Fixes #1928 
This PR will fix the regression when using a having condition in a query.

Fix the regression when using a having condition in a query.

---

src/QueryDataTable.php

Fix #2613
Reverts: #2611 and #2612

[9.x] Revert changes on count.

---

src/DataTableAbstract.php

Throw the original exception instead of wrapping it in a new exception

Don't trash the exception stack trace (#2714)

---

composer.json
tests/Http/Resources/UserResource.php

Support for Laravel 9

---

CONDUCT.md

Update Contributor Covenant

---

README.md

I tested it on Laravel 9, and it works perfectly, and I updated the min requirement to PHP 7.1 as composer.json says that too

Update README.md for Laravel 9 support

---

src/config/datatables.php

Fix `are` Word in Description

---

.github/workflows/continuous-integration.yml
.github/workflows/static-analysis.yml
src/CollectionDataTable.php
src/DataTableAbstract.php
src/QueryDataTable.php
tests/Integration/QueryDataTableTest.php

- Fix set total & filtered records count
- Fix #1453 #1454 #2050 #2609
- Add feature test
- Deprecate `skipTotalRecords`, just use `setTotalRecords` directly.

[10.x] Fix set total & filtered records count

---

src/QueryDataTable.php

This PR will fix sorting and pagination SQL on empty records

[9.x] Fix sorting and pagination on empty records

---

src/DataTableAbstract.php
tests/Integration/CollectionDataTableTest.php

[10.x] Fix null recordsFiltered on empty collection

---

src/EloquentDataTable.php
tests/Integration/HasOneThroughTest.php

I added the missing tests for the PR #2738 so that it can be merged. The original 2 commits are not my work, they belong to [RF1705](https://github.com/RF1705)
Related:
- #2738

[9.x] Fix HasOneThrough (added tests)

---

src/EloquentDataTable.php
tests/Integration/HasOneThroughTest.php

[10.x] Fix HasOneThrough

---

src/EloquentDataTable.php

[10.x] Fix relation key name for BelongsToMany

---

src/DataTableAbstract.php

Fix with method error with static analysis

---

README.md

Remove $ for easier copy paste of commands

---

.github/workflows/stale.yml

Add stale exempt labels, improve message

Adjust stale workflow config

---

src/DataTableAbstract.php
src/QueryDataTable.php

fix: prevent deprecation errors in php 8.1+

---

README.md
composer.json

feat: Laravel 10 compatibility

---

phpstan.neon.dist
src/Utilities/Request.php

Errors fixed:
```
Parameter #1 $value of function intval expects array|bool|float|int|resource|string|null, mixed given.
---
Negated boolean expression is always false.  
```

fix: phpstan

---

composer.json
phpstan.neon.dist

Starting with Larastan 2.7.0, the Larastan repository will now be managed under the Larastan organization.

fix: Update composer.json to use Larastan Org

---

README.md

docs: fix sponsors

---

README.md

docs: add datatables logo

---

tests/Integration/QueryDataTableTest.php

Tests to cover https://github.com/yajra/laravel-datatables/pull/3238 as request https://github.com/yajra/laravel-datatables/pull/3238#pullrequestreview-2828651945
I tried to cover all possible scenarios.

tests: Add tests to cover prefix detection

---

.github/workflows/semantic-release.yml
.releaserc.yml

- Added Semantic Release workflow using GitHub Actions
- Configured for automatic versioning, changelog updating, and GitHub release publishing
- Ensures consistent release management based on commit messages (following the conventional commits)

Add Semantic Release

---

.github/workflows/continuous-integration.yml

Test against php 8.5
